Repository SimulatedGREG/electron-vue, pull requests merged in 2018-10, with the labels that each got.

#698 add rule no-unused-expressions=off
  template/.eslintrc.js
  template/package.json
Labels: bug, discussion, in-progress

#629 command line Argument support for both yarn and npm
  docs/en/npm_scripts.md
  template/.electron-vue/dev-runner.js
Labels: enhancement

#692 Sync Vuex store between all processes
  docs/en/vue_accessories.md
  meta.js
  template/src/renderer/store/index.js
Labels: enhancement, in-progress, needs-docs
